services:
  db:
    image: mysql:latest
    container_name: revgas-db
    environment:
      MYSQL_ROOT_PASSWORD: admin
      MYSQL_DATABASE: revgas
      MYSQL_USER: admin
      MYSQL_PASSWORD: admin
    ports:
      - "3307:3306"
    volumes:
      - mysqldata:/var/lib/mysql

volumes:
  mysqldata:
